### ISSUE TITLE
Not Rendering?

### ISSUE THREAD

**Issue by JoshKasap** [omardelarosa/obsidian-mtg#19]
IDK if I'm just misunderstanding the documentation on how to use this or if some thing is actually wrong. I'm making a code block like this. 

````
``` mtg-decklist
4 Delver of Secrets // Insectile Aberration
4 Haughty Djinn
3 Tolarian Terror
4 Consider
4 Essence Scatter
4 Fading Hope
4 Make Disappear # consider Negate instead
4 Slip Out the Back
3 Spell Pierce
3 Thirst for Discovery
20 Island
1 Otawara, Soaring City
1 Otherworldly Gaze
1 Reckoner Bankbuster

Sideboard:
2 Disdainful Stroke
4 Negate
4 Out of the Way
1 Reckoner Bankbuster
4 Ertai's Scorn
```
````

But regardless of if I'm in preview or live preview/edit mode It just display's it like a basic code block. I double checked that the plugin was turned on and closed and re-opened obsidian but still no luck.

**Comment by ksonney** [comment]
The README appears to be incorrect, and you should use `mtg-deck` instead of `mtg-decklist`

**Comment by JoshKasap** [comment]
Yup this seemed to be the issue.

**Comment by omardelarosa** [comment]
@JoshKasap @ksonney sorry about the delay, this has been resolved now if you update to the latest version and the readme matches the plugin now.
