### ISSUE TITLE
Turn off pricing column option.

### ISSUE THREAD

**Issue by michael-byrd** [omardelarosa/obsidian-mtg#25]
Is there a way to turn off the price preview for deck lists?

I would love to use this plugin for organizing deck lists, but I am not interested in the cost of the cards.

**Comment by omardelarosa** [comment]
@michael-byrd there is!  I just added a new setting called `Show Prices`.  When This is toggled off, it should hide the price column:

<img width="786" alt="Screenshot 2023-09-25 at 11 27 59 PM" src="https://github.com/omardelarosa/obsidian-mtg/assets/2551722/206949c5-c4bc-4b8e-bec1-525da227fcd0">
