### ISSUE TITLE
Large deck support

### ISSUE THREAD

**Issue by Triquetra** [omardelarosa/obsidian-mtg#26]
I was excited to stumble on this plugin today, and I imported one of my decks from Moxfield.

Unfortunately, I found a minor issue. I play commander/EDH and the deck lists are 99 cards long (not counting the commander). The table generated by this plugin seems to stop producing links and hover pictures for cards around line 74 of my main deck list.

**Comment by omardelarosa** [comment]
@Triquetra I just pushed a fix for this in version 1.0.7 so go ahead and upgrade, restart and you should be able to see your EDH decks now.  Gonna close this issue but lmk if you spot anything else.

**Comment by omardelarosa** [comment]
Ah can you share a screenshot and maybe the decklist text so i can try to
reproduce? I will do some more testing tonight using the new version 1.0.7.

**Comment by Triquetra** [comment]
Here's the decklist text:
Commander
1 Brago, King Eternal
Main
1 Access Tunnel
1 Adarkar Wastes
1 Aerial Extortionist
1 Aether Channeler
1 Agent of Treachery
1 Angel of Serenity
1 Aqueous Form
1 Arcane Signet
1 Aven Fogbringer
1 Azorius Chancery
1 Azorius Signet
1 Benevolent Blessing
1 Blade Splicer
1 Blessed Sanctuary
1 Boss's Chauffeur
1 Celebrity Fencer
1 Chromatic Lantern
1 Cloudform
1 Command Tower
1 Darksteel Splicer
1 Deputy of Detention
1 Detention Sphere
1 Eldrazi Displacer
1 Ephara, God of the Polis
1 Exclusion Ritual
1 Felidar Guardian
1 Flaming Fist Officer
1 Flickering Ward
1 Geist-Honored Monk
1 Ghost Quarter
1 Ghostly Prison
1 Glacial Fortress
1 Glowing Anemone
1 Hero of Bretagard
10 Island
1 Kor Cartographer
1 Lavinia of the Tenth
1 Lightform
1 Loran of the Third Path
1 Malcator, Purity Overseer
1 Man-o'-War
1 Master Splicer
1 Meteor Golem
1 Minas Tirith
1 Nephalia Academy
1 Nevermaker
1 Nimbus Maze
1 Ninth Bridge Patrol
1 Panharmonicon
1 Pentarch Ward
10 Plains
1 Port Town
1 Prairie Stream
1 Propaganda
1 Protective Bubble
1 Ranar the Ever-Watchful
1 Reality Acid
1 Reliquary Tower
1 Restoration Angel
1 Rishadan Brigand
1 Rishadan Cutpurse
1 Rishadan Footpad
1 Rogue's Passage
1 Scroll of Fate
1 Sea of Clouds
1 Seachrome Coast
1 Sensor Splicer
1 Skycloud Expanse
1 Sol Ring
1 Solemn Simulacrum
1 Soulherder
1 Spectra Ward
1 Steel of the Godhead
1 Talisman of Progress
1 Thought Vessel
1 Unquestioned Authority
1 Venser, Shaper Savant
1 Ward of Lights
1 Whirler Rogue
1 Wing Splicer
1 Yorion, Sky Nomad

**Comment by Triquetra** [comment]
Here's a clip of the end of the list. Everything above this rendered properly. Note that this shot is with the "Show Prices" option disabled.
![2023-09-26 09_40_28-Blink and You're Dead 5DH - David - Obsidian v1 4 13](https://github.com/omardelarosa/obsidian-mtg/assets/195027/5da746c2-1045-48d9-bac0-ff43d666053f)

**Comment by omardelarosa** [comment]
I just tested with your deck using version 1.0.8.  It seems to be working now:

https://github.com/omardelarosa/obsidian-mtg/assets/2551722/498ee819-d322-4e8b-af63-de9a4f2fac47

Can you try updating on your end and see if it works now?

**Comment by Triquetra** [comment]
Confirmed working now. Thank you!
