### ISSUE TITLE
Add hover tooltip on cards with more info

### ISSUE THREAD

**Issue by omardelarosa** [omardelarosa/obsidian-mtg#4]

**Comment by leethobbit** [comment]
I was going to request something similar - if there's a good API/workflow for this, it would be wonderful to see a full card image as part of this.

**Comment by omardelarosa** [comment]
@leethobbit I think I'm going with the Scryfall API.  However, I don't know if it will be exactly a tooltip that hovers.  For now, it's just a panel with the card image on the bottom right of the component:

<img width="773" alt="Screen Shot 2022-10-09 at 8 09 32 PM" src="https://user-images.githubusercontent.com/2551722/194786569-a48ec33a-17b8-488a-9ee7-5ddb4450d1d8.png">

If I can figure out how to do the tooltip in the Obsidian UI, I'll come back to this tooltip idea then.
