### ISSUE TITLE
Possible to show buylist pricing from places like TCGplayer?

### ISSUE THREAD

**Issue by leethobbit** [omardelarosa/obsidian-mtg#8]
Maybe outside the scope of the app, but I'm guessing there's a way to pull pricing info from one of the online marketplaces.  I see that info in a lot of phone apps and it would be cool to see here.

Bonus points if we can see the total cost of missing cards in a deck based on said pricing.

**Comment by omardelarosa** [comment]
Good idea!  While I don't know if TCGPlayer has an API itself for it, I think the [Scryfall API](https://scryfall.com/docs/api) does have pricing info... that might be one way to add pricing info 🤔

**Comment by omardelarosa** [comment]
@leethobbit I started working on some of this in PR #9 .  I should having pricing and cost of missing cards up there soon in the next release
